language: c
sudo: required
#dist: trusty
before_install:
# Yara
  - wget https://github.com/plusvic/yara/archive/v3.5.0.tar.gz -O yara.tar.gz
  - tar -xzvf yara.tar.gz
# Androguard for Yara
  - wget https://raw.githubusercontent.com/Koodous/androguard-yara/master/androguard.c -O yara-3.5.0/libyara/modules/androguard.c
  - wget https://raw.githubusercontent.com/Koodous/androguard-yara/master/dist/yara-3.5.0/libyara/modules/module_list -O yara-3.5.0/libyara/modules/module_list
  - wget https://raw.githubusercontent.com/Koodous/androguard-yara/master/dist/yara-3.5.0/libyara/Makefile.am -O yara-3.5.0/libyara/Makefile.am
# libjansson
  - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz
  - tar -xzvf jansson-2.7.tar.gz
  - cd jansson-2.7
  - ./configure
  - make
  - sudo make install
  
# Compile Yara
  - cd ../yara-3.5.0
  - sed -i 's/#define RE_MAX_SPLIT_ID     128/#define RE_MAX_SPLIT_ID     255/g' libyara/re.c
  - ./bootstrap.sh
  - ./configure --enable-cuckoo
  - make
  - sudo make install
  - sudo ldconfig
  - cd ../

script:
  - echo "test" > testfile
  - echo "{}" > androguard_report.json
  - FALLO=0
  - for j in $(ls -d */); do for i in $(find $j -type f -name "*.yara" ; find $j -type f -name "*.yar"); do echo $i; yara -x androguard=androguard_report.json $i testfile; if [[ $? -ne 0 ]]; then FALLO=1; fi; done; done
  - exit $FALLO
